// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace VirtualGallery.Web.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SetIntro()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetIntro);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetCategories()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetCategories);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Category()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Category);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddCategory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditCategory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DropCategory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DropCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MoveCategory()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MoveCategory);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Upload()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Upload);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult TopPicture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopPicture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PreviewPicture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PreviewPicture);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditPicture()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPicture);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SetIntro = "SetIntro";
            public readonly string GetCategories = "GetCategories";
            public readonly string Category = "Category";
            public readonly string AddCategory = "AddCategory";
            public readonly string EditCategory = "EditCategory";
            public readonly string DropCategory = "DropCategory";
            public readonly string MoveCategory = "MoveCategory";
            public readonly string Upload = "Upload";
            public readonly string TopPicture = "TopPicture";
            public readonly string PreviewPicture = "PreviewPicture";
            public readonly string EditPicture = "EditPicture";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SetIntro = "SetIntro";
            public const string GetCategories = "GetCategories";
            public const string Category = "Category";
            public const string AddCategory = "AddCategory";
            public const string EditCategory = "EditCategory";
            public const string DropCategory = "DropCategory";
            public const string MoveCategory = "MoveCategory";
            public const string Upload = "Upload";
            public const string TopPicture = "TopPicture";
            public const string PreviewPicture = "PreviewPicture";
            public const string EditPicture = "EditPicture";
        }


        static readonly ActionParamsClass_SetIntro s_params_SetIntro = new ActionParamsClass_SetIntro();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetIntro SetIntroParams { get { return s_params_SetIntro; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetIntro
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_GetCategories s_params_GetCategories = new ActionParamsClass_GetCategories();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetCategories GetCategoriesParams { get { return s_params_GetCategories; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetCategories
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Category s_params_Category = new ActionParamsClass_Category();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Category CategoryParams { get { return s_params_Category; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Category
        {
            public readonly string categoryId = "categoryId";
        }
        static readonly ActionParamsClass_AddCategory s_params_AddCategory = new ActionParamsClass_AddCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddCategory AddCategoryParams { get { return s_params_AddCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddCategory
        {
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_EditCategory s_params_EditCategory = new ActionParamsClass_EditCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditCategory EditCategoryParams { get { return s_params_EditCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditCategory
        {
            public readonly string id = "id";
            public readonly string name = "name";
        }
        static readonly ActionParamsClass_DropCategory s_params_DropCategory = new ActionParamsClass_DropCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DropCategory DropCategoryParams { get { return s_params_DropCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DropCategory
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_MoveCategory s_params_MoveCategory = new ActionParamsClass_MoveCategory();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MoveCategory MoveCategoryParams { get { return s_params_MoveCategory; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MoveCategory
        {
            public readonly string id = "id";
            public readonly string up = "up";
        }
        static readonly ActionParamsClass_Upload s_params_Upload = new ActionParamsClass_Upload();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Upload UploadParams { get { return s_params_Upload; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Upload
        {
            public readonly string categoryId = "categoryId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_TopPicture s_params_TopPicture = new ActionParamsClass_TopPicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_TopPicture TopPictureParams { get { return s_params_TopPicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_TopPicture
        {
            public readonly string id = "id";
            public readonly string top = "top";
        }
        static readonly ActionParamsClass_PreviewPicture s_params_PreviewPicture = new ActionParamsClass_PreviewPicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PreviewPicture PreviewPictureParams { get { return s_params_PreviewPicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PreviewPicture
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditPicture s_params_EditPicture = new ActionParamsClass_EditPicture();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditPicture EditPictureParams { get { return s_params_EditPicture; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditPicture
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _AddCategoryButton = "_AddCategoryButton";
                public readonly string _AddPictureButton = "_AddPictureButton";
                public readonly string _Categories = "_Categories";
                public readonly string _Gallery = "_Gallery";
                public readonly string _Layout = "_Layout";
                public readonly string _Picture = "_Picture";
                public readonly string _PicturePreviewDialog = "_PicturePreviewDialog";
                public readonly string _Pictures = "_Pictures";
                public readonly string Category = "Category";
                public readonly string Index = "Index";
            }
            public readonly string _AddCategoryButton = "~/Views/Home/_AddCategoryButton.cshtml";
            public readonly string _AddPictureButton = "~/Views/Home/_AddPictureButton.cshtml";
            public readonly string _Categories = "~/Views/Home/_Categories.cshtml";
            public readonly string _Gallery = "~/Views/Home/_Gallery.cshtml";
            public readonly string _Layout = "~/Views/Home/_Layout.cshtml";
            public readonly string _Picture = "~/Views/Home/_Picture.cshtml";
            public readonly string _PicturePreviewDialog = "~/Views/Home/_PicturePreviewDialog.cshtml";
            public readonly string _Pictures = "~/Views/Home/_Pictures.cshtml";
            public readonly string Category = "~/Views/Home/Category.cshtml";
            public readonly string Index = "~/Views/Home/Index.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : VirtualGallery.Web.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SetIntroOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, VirtualGallery.Web.Models.Home.HtmlModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult SetIntro(VirtualGallery.Web.Models.Home.HtmlModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SetIntro);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SetIntroOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void GetCategoriesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetCategories(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetCategories);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            GetCategoriesOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void CategoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int categoryId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Category(int categoryId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Category);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "categoryId", categoryId);
            CategoryOverride(callInfo, categoryId);
            return callInfo;
        }

        [NonAction]
        partial void AddCategoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string name);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddCategory(string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            AddCategoryOverride(callInfo, name);
            return callInfo;
        }

        [NonAction]
        partial void EditCategoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, string name);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditCategory(int id, string name)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "name", name);
            EditCategoryOverride(callInfo, id, name);
            return callInfo;
        }

        [NonAction]
        partial void DropCategoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DropCategory(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DropCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DropCategoryOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void MoveCategoryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, bool up);

        [NonAction]
        public override System.Web.Mvc.ActionResult MoveCategory(int id, bool up)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MoveCategory);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "up", up);
            MoveCategoryOverride(callInfo, id, up);
            return callInfo;
        }

        [NonAction]
        partial void UploadOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int categoryId, VirtualGallery.Web.Models.Home.PictureUploadButtonModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult Upload(int categoryId, VirtualGallery.Web.Models.Home.PictureUploadButtonModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Upload);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "categoryId", categoryId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            UploadOverride(callInfo, categoryId, model);
            return callInfo;
        }

        [NonAction]
        partial void TopPictureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id, bool top);

        [NonAction]
        public override System.Web.Mvc.ActionResult TopPicture(int id, bool top)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.TopPicture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "top", top);
            TopPictureOverride(callInfo, id, top);
            return callInfo;
        }

        [NonAction]
        partial void PreviewPictureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int id);

        [NonAction]
        public override System.Web.Mvc.ActionResult PreviewPicture(int id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PreviewPicture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PreviewPictureOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void EditPictureOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, VirtualGallery.Web.Models.Home.PictureModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult EditPicture(VirtualGallery.Web.Models.Home.PictureModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditPicture);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditPictureOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
