// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace VirtualGallery.Web.Controllers
{
    public partial class ShoppingCartController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShoppingCartController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CartDialog()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CartDialog);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MakeOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MakeOrder);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DropOrder()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DropOrder);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShoppingCartController Actions { get { return MVC.ShoppingCart; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ShoppingCart";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ShoppingCart";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CartDialog = "CartDialog";
            public readonly string MakeOrder = "MakeOrder";
            public readonly string Orders = "Orders";
            public readonly string DropOrder = "DropOrder";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CartDialog = "CartDialog";
            public const string MakeOrder = "MakeOrder";
            public const string Orders = "Orders";
            public const string DropOrder = "DropOrder";
        }


        static readonly ActionParamsClass_CartDialog s_params_CartDialog = new ActionParamsClass_CartDialog();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CartDialog CartDialogParams { get { return s_params_CartDialog; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CartDialog
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_MakeOrder s_params_MakeOrder = new ActionParamsClass_MakeOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MakeOrder MakeOrderParams { get { return s_params_MakeOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MakeOrder
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_DropOrder s_params_DropOrder = new ActionParamsClass_DropOrder();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DropOrder DropOrderParams { get { return s_params_DropOrder; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DropOrder
        {
            public readonly string orderId = "orderId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _OrdersDialog = "_OrdersDialog";
                public readonly string _ShoppingCartDialog = "_ShoppingCartDialog";
            }
            public readonly string _OrdersDialog = "~/Views/ShoppingCart/_OrdersDialog.cshtml";
            public readonly string _ShoppingCartDialog = "~/Views/ShoppingCart/_ShoppingCartDialog.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ShoppingCartController : VirtualGallery.Web.Controllers.ShoppingCartController
    {
        public T4MVC_ShoppingCartController() : base(Dummy.Instance) { }

        [NonAction]
        partial void CartDialogOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, VirtualGallery.Web.Models.ShoppingCart.CartModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult CartDialog(VirtualGallery.Web.Models.ShoppingCart.CartModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CartDialog);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CartDialogOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void MakeOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, VirtualGallery.Web.Models.ShoppingCart.OrderModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult MakeOrder(VirtualGallery.Web.Models.ShoppingCart.OrderModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MakeOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            MakeOrderOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void OrdersOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Orders()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Orders);
            OrdersOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DropOrderOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int orderId);

        [NonAction]
        public override System.Web.Mvc.ActionResult DropOrder(int orderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DropOrder);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderId", orderId);
            DropOrderOverride(callInfo, orderId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
